site_name: "Music Server Documentation"
site_url: "https://docs.jimbrig.com/music-server/"
site_description: "Documentation for the my personal Music Server."
site_author: "Jimmy Briggs <jimmy.briggs@jimbrig.com>"
copyright: "Jimmy Briggs | 2023"
repo_url: "https://github.com/jimbrig/music-server"
edit_uri: "blob/main/docs/"
remote_branch: "gh-pages"
remote_name: "origin"

docs_dir: "docs"
site_dir: "site"

theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "blue"
    toggle:
      icon: "menu"
      name: "Menu"

nav:
  - Home: "index.md"
  - About:
      - "about/index.md"
      - "License": "about/license.md"
      - "Contributing": "about/contributing.md"
      - "Code of Conduct": "about/code-of-conduct.md"
      - "Security": "about/security.md"
      - "Roadmap": "about/roadmap.md"
      - "Credits": "about/credits.md"
      - "Changelog": "about/changelog.md"
      - "FAQ": "about/faq.md"
  - "Overview":
      - "overview/index.md"
      - "Installation": "overview/installation.md"
      - "Configuration": "overview/configuration.md"
      - "Usage": "overview/usage.md"
      - "Troubleshooting": "overview/troubleshooting.md"
  - "Development":
      - "development/index.md"
      - "Development Environment": "development/devenv.md"
      - "Library": "development/library.md"
      - "Data": "development/data.md"
      - "API": "development/api.md"
      - "UI": "development/ui.md"
      - "Testing": "development/testing.md"
      - "Deployment": "development/deployment.md"
      - "Tools":
          - "development/tools/index.md"
          - "Navidrome":
              - "development/tools/navidrome/index.md"
              - "Docker": "development/tools/navidrome/docker.md"
              - "Configuration": "development/tools/navidrome/configuration.md"
              - "Integrations": "development/tools/navidrome/integrations.md"
          - "Beets":
              - "development/tools/beets/index.md"
              - "Configuration": "development/tools/beets/configuration.md"
              - "Plugins": "development/tools/beets/plugins.md"
          - "MusicBrainz":
              - "development/tools/musicbrainz/index.md"
              - "Configuration": "development/tools/musicbrainz/configuration.md"
              - "MusicBrainz Picard": "development/tools/musicbrainz/picard.md"
              - "Plugins": "development/tools/musicbrainz/plugins.md"
      - "Server":
          - "development/server/index.md"
          - "Architecture": "development/server/architecture.md"
          - "Security": "development/server/security.md"
