LogLevel = 'DEBUG'
EnableLogRedacting = false
Port = 4533
AutoImportPlaylists = true
PlaylistsPath = ".:**/**"
UIWelcomeMessage = "Welcome to Jimmy's Music Library Media Server!"
DefaultTheme = 'Dark'
EnableCoverAnimation = true
EnableDownloads = true
EnableGravatar = true
ScanSchedule = '@every 1h'
TranscodingCacheSize = '150MiB'
MusicFolder = './data/music'
EnableExternalServices = true
EnableFavourites = true
EnableUserEditing = true
LastFM.Enabled = true
LastFM.Language = 'en'
ListenBrainz.Enabled = true
